import type { Metadata } from 'next'
import { Roboto } from 'next/font/google' //избрахме си font да ни е Roboto
import './globals.css'
import { Header } from './components/layouts/Header'

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] }) //и тук си го сетваме

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }:
  {
    children: React.ReactNode
  }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className='max-w-4xl mx-auto p-4'>
          <Header />
          {children}
          <footer className='border-t p-8 text-center text-gray-400'>
            &copy; 2024 All right reserved
          </footer>
        </main>
      </body>
    </html>
  )
}


//<main className='max-w-4xl mx-auto p-4'>
//{children}
//</main>
//чрез този className си сетнахме app да ни е централно и да има
//въздух от лявата и дясната страна на цялото приложение 